---
- name: Install and enable nginx for a website
  hosts: rhel
  become: false
  tasks:
    - name: Update all packages to latest

    - name: Install nginx

    - name: Set https allow firewall rule

    - name: Enable nginx service
