---
- name: Deploy EC2 Instance
  hosts: localhost
  become: false
  vars:
    region: us-east-1
    image_id: ami-123456
    vpc_id: vpc-12345
    vpc_subnet_id: subnet-12345
    key_name: key-12345
    instance_type: t2.micro
    aws_access_key: "{{ lookup('env', 'ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env', 'SECRET_KEY') }}"
  tasks:
    - name: Create a security group to allow https
      amazon.aws.ec2_security_group:
        name: webserver-security-group
        description: Security Group for Webserver
        region: us-east-1
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
      register: sec_grp

    - name: Create an EC2 instance
      amazon.aws.ec2_instance:
        name: EC2 Instance
        key_name: "{{ key_name }}"
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        instance_type: t2.micro
        security_group: webserver-security-group
        image_id: "{{ image_id }}"
        wait: true
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        network:
          assign_public_ip: true
      register: ec2

    - name: Add host to group named rhel
      ansible.builtin.add_host:
        hostname: "{{ ec2.public_ip }}"
        groups: rhel

- name: Install and enable nginx for a website
  hosts: rhel
  become: true
  tasks:
    - name: Update all packages to latest
      ansible.builtin.package:
        name: '*'
        state: latest

    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Set https allow firewalld rule
      ansible.posix.firewalld:
        port: 443/tcp
        permanent: true
        state: enabled
        immediate: true

    - name: Enable nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
